grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
    - grafana.34.73.227.173.nip.io
prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
    - prometheus.34.73.227.173.nip.io
  # prometheusSpec:
  #   additionalScrapeConfigs:
  #   # Istio
  #   - job_name: istiod
  #     kubernetes_sd_configs:
  #     - role: endpoints
  #       namespaces:
  #         names:
  #         - istio-system
  #     relabel_configs:
  #     - source_labels:
  #       - __meta_kubernetes_service_name
  #       - __meta_kubernetes_endpoint_port_name
  #       action: keep
  #       regex: istiod;http-monitoring
  #   - job_name: envoy-stats
  #     metrics_path: /stats/prometheus
  #     kubernetes_sd_configs:
  #     - role: pod
  #     relabel_configs:
  #     - source_labels:
  #       - __meta_kubernetes_pod_container_port_name
  #       action: keep
  #       regex: .*-envoy-prom
  #   # OpenCost
  #   - job_name: opencost
  #     honor_labels: true
  #     scrape_interval: 1m
  #     scrape_timeout: 10s
  #     metrics_path: /metrics
  #     scheme: http
  #     dns_sd_configs:
  #     - names:
  #       - opencost.opencost
  #       type: 'A'
  #       port: 9003
